name: pysh
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - expat
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - affine
      - anyio
      - appnope
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - async-lru
      - attrs
      - babel
      - beautifulsoup4
      - bleach
      - cartopy
      - certifi
      - cffi
      - cftime
      - charset-normalizer
      - click
      - click-plugins
      - cligj
      - comm
      - contourpy
      - cycler
      - debugpy
      - decorator
      - defusedxml
      - executing
      - fastjsonschema
      - fonttools
      - fqdn
      - geopandas
      - h11
      - httpcore
      - httpx
      - idna
      - ipykernel
      - ipython
      - isoduration
      - jedi
      - jinja2
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - julian
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - kiwisolver
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mistune
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - netcdf4
      - notebook-shim
      - numpy
      - overrides
      - packaging
      - pandas
      - pandocfilters
      - parso
      - pexpect
      - pillow
      - platformdirs
      - prometheus-client
      - prompt-toolkit
      - psutil
      - ptyprocess
      - pure-eval
      - pycparser
      - pygments
      - pyogrio
      - pyparsing
      - pyproj
      - pyshbundle
      - pyshp
      - python-dateutil
      - python-json-logger
      - pytz
      - pyyaml
      - pyzmq
      - rasterio
      - referencing
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - rioxarray
      - rpds-py
      - scipy
      - send2trash
      - shapely
      - six
      - sniffio
      - snuggs
      - soupsieve
      - stack-data
      - terminado
      - tinycss2
      - tornado
      - tqdm
      - traitlets
      - types-python-dateutil
      - tzdata
      - uri-template
      - urllib3
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - xarray