name: mc
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - importlib_metadata
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - krb5
  - libblas
  - libcblas
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libopenblas
  - libsodium
  - libsqlite
  - libzlib
  - llvm-openmp
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - numpy
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
      - affine
      - anyio
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - async-lru
      - attrs
      - babel
      - beautifulsoup4
      - bleach
      - cartopy
      - certifi
      - cffi
      - cftime
      - charset-normalizer
      - click
      - click-plugins
      - cligj
      - contourpy
      - cycler
      - defusedxml
      - fastjsonschema
      - fonttools
      - fqdn
      - geopandas
      - h11
      - httpcore
      - httpx
      - idna
      - importlib-resources
      - ipykernel
      - isoduration
      - jinja2
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - julian
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - kiwisolver
      - markupsafe
      - matplotlib
      - mistune
      - nbclient
      - nbconvert
      - nbformat
      - netcdf4
      - notebook-shim
      - overrides
      - pandas
      - pandocfilters
      - pillow
      - prometheus-client
      - pycparser
      - pyogrio
      - pyparsing
      - pyproj
      - pyshbundle
      - pyshp
      - python-json-logger
      - pytz
      - pyyaml
      - rasterio
      - referencing
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - rioxarray
      - rpds-py
      - send2trash
      - shapely
      - sniffio
      - soupsieve
      - terminado
      - tinycss2
      - tomli
      - tqdm
      - types-python-dateutil
      - tzdata
      - uri-template
      - urllib3
      - webcolors
      - webencodings
      - websocket-client
      - xarray