name: ci-docs-gh-pages
on:
  push:
    branches:
      - main
      - joss-review-7550

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache MkDocs dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-${{ hashFiles('requirements.txt') }}
          path: .cache

      - name: Install MkDocs dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mkdocs-jupyter

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
