name: Build and test

on: [push]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pysh
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install package
        run: pip install .
      - name: Test with unittest
        run: |
          python -m unittest tests/test_pyshbundle.py